#ifndef __CG_UART_H__
#define __CG_UART_H__

typedef enum {
	CMD_ERR					= 0xFF,
	CMD_SYS_INFO 			= 0x20,
	CMD_PB_STATUS 			= 0x21,
	CMD_SYS_STATUS 			= 0x23,
	CMD_KEY 				= 0x40,
	CMD_RESOLUTION	 		= 0x50,
	CMD_TIME 				= 0x51,
	CMD_REC_CYCLE_TIME 		= 0x52,
	CMD_REC_AUDIO 			= 0x53,
	CMD_LANGUAGE 			= 0x54,
	CMD_GSENSOR_STATUS		= 0x55,
	CMD_LIGHT_FREQ 			= 0x56,
	CMD_DATE_FORMAT 		= 0x57,
	CMD_SYS_DATE 			= 0x58,
	CMD_SYS_TIME 			= 0x59,
	CMD_GET_VERSION			= 0x5A,
	CMD_FORMAT				= 0x5B,
	CMD_REQUEST_SYS_PARAM	= 0x5C,
	CMD_SYS_DATE_TIME		= 0x5D,
	CMD_SET_SYS_PARAM 		= 0x5F,
	CMD_SEND_FILENAME		= 0x70,
	CMD_CUR_PAGE_FILENAMES 	= 0x71,
	CMD_PLAY_FILE			= 0x72,
	CMD_POWEROFF			= 0x22,
	CMD_GET_REC_TIME		= 0x24,
	CMD_GET_ELAPSED_TIME	= 0x25,
	CMD_GET_PB_DURATION		= 0x26,
	
	
	CMD_ERROR = 0xFF,
} CG_UART_CMD;

#endif

